<?php
include "../include/db.php";
include_once "../include/general.php";
include "../include/authenticate.php"; 
include "../include/resource_functions.php";
include "../include/collections_functions.php";
include "../include/header.php";


global $base_url;

$ref=getvalescaped("ref","",true);
$all_resources =  get_collection_resources($ref) ;
echo get_resource_path(3,false,"col",$generate=true,$extension="png",$scramble=-1,$page=1,$watermarked=false,$file_modified="",$alternative=-1,$includemodified=true);


//echo parse_url(get_resource_path(3,false,"col",$generate=true,$extension="jpg",$scramble=-1,$page=1,$watermarked=false,$file_modified="",$alternative=-1,$includemodified=true), PHP_URL_PATH);
$markers = array();
$mean_lat=0;
$mean_long=0;
foreach ($all_resources as $value) {
    
    $resource = get_resource_data($value,$cache=true);
    //print_r( $resource );
echo $resource['ref'];
    $markers[] =  [ $resource['geo_long'] . "," .  $resource['geo_lat'] . "," . $resource['ref'] ];
    $mean_lat=$mean_lat+$resource['geo_lat'];
    $mean_long=$mean_long+$resource['geo_long'];  
    }

$mean_lat=$mean_lat/count($markers);
$mean_long=$mean_long/count($markers);


?>

<h1><?php echo $lang["geolocatecollection"] ?></h1>

  <div id="GeoColDiv" style="width:700px; height:300px;"></div>
  
 <script src="http://www.openlayers.org/api/OpenLayers.js"></script>
  <script>


    map = new OpenLayers.Map("GeoColDiv");
    map.addLayer(new OpenLayers.Layer.OSM());
    epsg4326 =  new OpenLayers.Projection("EPSG:4326"); //WGS 1984 projection
    projectTo = map.getProjectionObject(); //The map projection (Spherical Mercator)
   
    var lonLat = new OpenLayers.LonLat(  <?php echo $mean_long . "," . $mean_lat;?> ).transform(epsg4326, projectTo);
          
    var zoom=14;
    map.setCenter (lonLat, zoom);

    var vectorLayer = new OpenLayers.Layer.Vector("Overlay");
    
    // Define an array. This could be done in a seperate js file.
    // This tidy formatted section could even be generated by a server-side script (jsonp)

    var markers = <?php echo str_replace('"','',json_encode($markers)) ?>;

    //Loop through the markers array
    for (var i=0; i<markers.length; i++) {
      
       var lon = markers[i][0];
       var lat = markers[i][1];
       var rf = String(markers[i][2]);
       //alert(rf);
       var feature = new OpenLayers.Feature.Vector(
                new OpenLayers.Geometry.Point( lon, lat ).transform(epsg4326, projectTo),
               {description: "Resource ID:" + rf},
                {externalGraphic: '../lib/OpenLayers/img/marker.png', graphicHeight: 25, graphicWidth: 21, graphicXOffset:-12, graphicYOffset:-25 }
            );   
		      
    
        vectorLayer.addFeatures(feature);

    }                        
      
    map.addLayer(vectorLayer);

//Add a selector control to the vectorLayer with popup functions
    var controls = {
      selector: new OpenLayers.Control.SelectFeature(vectorLayer, { onSelect: createPopup, onUnselect: destroyPopup })
    };

    function createPopup(feature) {
      feature.popup = new OpenLayers.Popup.FramedCloud("pop",
          feature.geometry.getBounds().getCenterLonLat(),
          null,
          '<div class="markerContent">'+feature.attributes.description+'</div>',
          null,
          true,
          function() { controls['selector'].unselectAll(); }
      );
      //feature.popup.closeOnMove = true;
      map.addPopup(feature.popup);
    }

    function destroyPopup(feature) {
      feature.popup.destroy();
      feature.popup = null;
    }
    
    map.addControl(controls['selector']);
    controls['selector'].activate();


</script>


<?php
include "../include/footer.php";
?>
